---
- name: Install Needed package for guacamole
  yum: state=installed pkg={{item}}
  with_items:
    - cairo-devel
    - libpng-devel
    - uuid-devel
    - freerdp-devel
    - freerdp
    - pango-devel
    - libssh2-devel
    - libvncserver-devel
    - pulseaudio-libs-devel
    - openssl-devel
    - libvorbis-devel
    - wget
    - gcc
    - http://dl.fedoraproject.org/pub/epel/6/x86_64/libtelnet-0.20-2.el6.x86_64.rpm
    - http://dl.fedoraproject.org/pub/epel/6/x86_64/libtelnet-devel-0.20-2.el6.x86_64.rpm
- file:  path=/var/lib/guacamole/classpath state=directory mode=0755 
- name: download file guacamole server with sha256 check
  get_url: url=http://sourceforge.net/projects/guacamole/files/current/source/guacamole-server-0.9.7.tar.gz/download dest=/tmp/guacamole-server-0.9.7.tar.gz sha256sum=285f367d89ee51981db84b00698b05b3d9ba5de2fb2922115c9e38d2b9b88d09
- name: executing guacamole server
  shell: cd /tmp; tar -zxvf guacamole-server-0.9.7.tar.gz; cd guacamole-server-0.9.7;./configure --with-init-dir=/etc/init.d ; make ; make install
- name: Start guacd service
  service: name=guacd state=started enabled=yes
- name: download file guacamole cclient
  get_url: url=http://sourceforge.net/projects/guacamole/files/current/binary/guacamole-0.9.7.war/download dest=/opt/tomcat/webapps/guacamole.war sha256sum=4364d8f18454a40849136b2728a2d701778333567dd848a3fada087da7abe15a
- name: install mysql
  yum: state=installed pkg=mysql-server
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
- name: install mariadb
  yum: state=installed pkg=mariadb-server
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
- file: path=/root/.guacamole state=directory mode=0755
- name: Start tomcat service
  service: name={{item}} state=started enabled=yes
  with_items:
    - tomcat
    - mysqld 
- name: Upload guacamole preoperties
  copy: src={{item.src}} dest={{item.dest}} mode=0755
  with_items: 
    - { src: 'guacamole.properties' , dest: '/root/.guacamole/guacamole.properties' }
    - { src: 'guacamole-auth-jdbc-mysql-0.9.7.jar' , dest: '/var/lib/guacamole/classpath/guacamole-auth-jdbc-mysql-0.9.7.jar' }
    - { src: 'mysql-connector-java-5.1.35-bin.jar' , dest: '/var/lib/guacamole/classpath/mysql-connector-java-5.1.35-bin.jar' }
    - { src: 'initdb.sql', dest: '/tmp/guacamole_initdb.sql' }
- name: Database existance checking
  shell: mysql -u root -e 'show databases' | grep guacamole_db
  register: dbstatus
- name: Database status print
  debug: msg="{{dbstatus}}"
- name: Initializing database
  shell: mysql -u root < /tmp/guacamole_initdb.sql
  when: dbstatus|failed
